### ISSUE TITLE
Capability of measuring more than 60 Fps

### ISSUE THREAD

**Issue by C4s4r** [gskinnerTeam/flutter-stats-fl#1]
I'm trying to set the DisplayMode of my App to 90 Hz by using [this](https://pub.dev/packages/flutter_displaymode) package.
Besides I'm using the StatsFl-Package to track if it's working. Currently I'm not sure if this package is capable of measuring more than 60 Fps - as it looks like locked to 60 Fps max. Would be helpful if I could be sure the problem is not on the side of StatsFl.

Thanks for any help!

**Comment by esDotDev** [comment]
As a quick fix this should work:
Line78:
```
var maxFps = 90;
 _fps = min((_ticks * 1000 / sampleTimeMs).roundToDouble(), maxFps);
```

I'll push an update to fix sometime soon. Or you can make a PR :)

**Comment by C4s4r** [comment]
Thanks for the fast fix! No PR for the fix needed, as you already solved it pretty quick 👍 
Just added the entry in the readme to let others know that this is possible now.

**Comment by esDotDev** [comment]
Ya, figured I might as well just do it :) Thanks for the readme fix
