### ISSUE TITLE
120hz iPhone 13 pro max

### ISSUE THREAD

**Issue by jalal-zy** [gskinnerTeam/flutter-stats-fl#6]
Did you test it on 120hz?
I put max fps 120 
but it always prints 20-60

**Comment by litang0908** [comment]
If your flutter project really support 120Hz, it will show like this:
![image](https://user-images.githubusercontent.com/44760239/161889500-d904127a-9d72-472c-93de-def194c9026c.png)

The value doesn't display correctly , but not the error you got, if it always prints 20-60, maybe that you are not on 120hz.

**Comment by esDotDev** [comment]
Fixed: https://github.com/gskinnerTeam/flutter-stats-fl/pull/7
